[package]
name = "alleakator"
description = "leaking global allocator"
version = "1.0.0"
repository = "https://github.com/TimonPasslick/alleakator"
license = "MIT"
authors = ["Timon Paßlick <timon.passlick@gmx.de>"]
edition = "2018"

[dependencies]
